# Generated by Django 5.2.5 on 2026-01-12 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_featured_image_alter_post_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='featured_image2',
            field=models.ImageField(blank=True, null=True, upload_to='static/featured/'),
        ),
    ]
